### ISSUE TITLE
Calling C# method from SciterJS (QuickJS) script 

### ISSUE THREAD

**Issue by vrimar** [wdcossey/SciterCore#32]
Unless I'm missing something, I can't seem to call a C# method from a QuickJS script in the `Samples/HelloSciterJS` project.

I've tried doing the following with no success:

`Window.this.SynchronousFunction()`
`globalThis.SynchronousFunction()`
`view.SynchronousFunction()`
`SynchronousFunction()`

**Comment by wdcossey** [comment]
Hey @vrimar,

I am aware of this, I can't get it working either. 😞 else it would be in the sample app, from what I have read `Window.this.xxx()` should be correct.

I will check if there's an issue with the sciter-js library (it's still in development), I'll post an update when I have more information.

**Comment by vrimar** [comment]
I found this [link](https://sciter.com/forums/topic/call_function-with-sciter-js-not-working/) on the sciter forums. Looks like the issue has been fixed but a new version hasn't been published yet.

**Comment by wdcossey** [comment]
Haha, yeah I added a comment earlier.

I am sure you have read what Andrew said, it should be `Window.this.call("func", ..params..)`.

Interestingly he said `will be something` so I assume it's not implemented as of yet.

**Comment by wdcossey** [comment]
@vrimar 

[Here's](https://github.com/c-smile/sciter-js-sdk/discussions/30#discussioncomment-267512) an update for you regarding the status of the implementation.

Regards,
Will.

**Comment by vrimar** [comment]
Perfect! Thank you for all your hard work in porting to .NET core @wdcossey!

**Comment by wdcossey** [comment]
@vrimar I have updated the SciterCore.JS samples to show use of `Window.this.xcall("<MethodName>" [, ...args..])` from the latest SciterJS update `4.4.5.10`

For more info on `Window.this.xcall()` see the documentation [here](https://github.com/c-smile/sciter-js-sdk/wiki/Window#methods)
