### ISSUE TITLE
4.4.7.2 SciterCreateWindow is null

### ISSUE THREAD

**Issue by christan-duplicate** [wdcossey/SciterCore#37]
4.4.7.2 SciterCreateWindow is null

**Comment by wdcossey** [comment]
'SciterCore' supports backwards compatibility with a number of versions of Sciter (from version 4.4.0.3 and up) using dynamic structure bindings.

I'll have to update the bindings to add support for the new 'UnifiedApi' from version 4.4.7.0, should be simple enough.

**Comment by christan-duplicate** [comment]
> `SciterCore` supports backwards compatibility with a number of versions of Sciter (from version `4.4.0.3` and up) using dynamic structure bindings.
> 
> I'll have to update the bindings to add support for the new `UnifiedApi` from version `4.4.7.0`, should be simple enough.

thank you.

**Comment by christan-duplicate** [comment]
SciterOpenArchive is also null ...

**Comment by wdcossey** [comment]
@christan-duplicate 

Is this related to `SciterCore` or `SciterCore.JS`?

Are you using the package (from NuGet)? if so what version and what version on the Binaries?
If you are using the source directly could you please post a code sample/block?

I am testing it locally (using the source) and I don't have any issues but that doesn't mean there aren't any.

**Comment by christan-duplicate** [comment]
> @christan-duplicate
> 
> Is this related to `SciterCore` or `SciterCore.JS`?
> 
> Are you using the package (from NuGet)? if so what version and what version on the Binaries?
> If you are using the source directly could you please post a code sample/block?
> 
> I am testing it locally (using the source) and I don't have any issues but that doesn't mean there aren't any.

It's alright, it's my problem, thank you.

**Comment by wdcossey** [comment]
@christan-duplicate 

No worries, glad you got it working 👍 

I pushed some changes and a new NuGet version earlier.
