### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by pravic** [wdcossey/SciterCore#39]
Hey, just chiming in to say hi and thank you for this project. It's a great improvement over the predecessor.

**Comment by wdcossey** [comment]
Hey @pravic 

I see you contributing and commenting often on the official repos/forums, thanks for your comments, greatly appreciated 😃 

There's still loads of improvements/ideas planned, hopefully I'll get some time to get to them soon (esp. with adding support for .Net Core in MacOS w/o Xamarin)
