### ISSUE TITLE
Upcoming work & desired future state?

### ISSUE THREAD

**Issue by svengeance** [wdcossey/SciterCore#46]
Hey man, thanks for porting this to .NET Core! I'm interested in trying out Sciter w/ a Native AOT Compiled Net5/Net6 app; this will get me quite a ways there.

I'm curious what your plans are for this Core port? Obviously to maintain parity with the previous iteration; what other interests do you have? I'll be working with this project to get it working as-needed with AOT scenarios, and if that's of interest to you, I'd be glad to upstream some of the changes.

**Comment by wdcossey** [comment]
Hey @svengeance,

Thanks for the message. 😃 

I assume you are talking about Ahead-Of-Time compilation?

My plans are to extend this beyond the original project (SciterSharp) and drop the need for some platform specific packages (i.e Xamarin, GTK, etc).
I am working on a port of `libui` (you'll find it on GitHub), that will replace some of the PInvoke/Xamarin code in SciterCore, though it'll be implemented via PInvoke itself; it's once place to manage MacOS, Linux and Windows.

You are welcome to have a poke around, make changes, make requests, put in a PR, etc there's a bunch more things to do and a lot of cleaning up on the cards.

My time is limited at the moment but I will get back to this project later this month, if you have a repo that you are working on and want to show me what you are up to drop a link.

**Comment by svengeance** [comment]
I will be more than glad to when I make the project public - I've put it on pause to focus on my career for a minute and accidentally burned myself out on Leetcode exercises. I'll be excited to see how you integrate LibUI with it.
And yeah - Native Ahead-of-Time compilation. 

As a request I suppose - maybe consider creating some issues for small work you would like? I see you've cleaned up this project a lot from the original and it looks great. I'll close this so it doesn't take up space.

Cheers! <3
