### ISSUE TITLE
SciterCore.HelloSciter and SciterCore.JS.HelloSciter are always reported "SciterCreateWindow is for use on Windows" on Ubuntu 

### ISSUE THREAD

**Issue by goodtogood** [wdcossey/SciterCore#49]
Hi, I found SciterCore via search tool
It's a great work .
I got some problems when trying SciterCore

**System information (version)**

- SciterCore => [Latest](https://github.com/wdcossey/SciterCore/commit/0d190196a9507476070698d9f742a383d3a1025b)
- Operating System / Platform => Windows 10 64 Bit / Ubuntu 20.04 64bit
- Compiler => Visual Studio 2019
- .Net => 5.0

**Detailed description**

SciterCore.JS.HelloSciter or SciterCore.HelloSciter was published via config as below

```
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>Any CPU</Platform>
    <PublishDir>bin\Release\net5.0\publish\</PublishDir>
    <PublishProtocol>FileSystem</PublishProtocol>
    <TargetFramework>net5.0</TargetFramework>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>True</PublishSingleFile>
    <PublishTrimmed>True</PublishTrimmed>
    <TrimMode>Link</TrimMode>
  </PropertyGroup>
</Project>

```
unhandled exception occurred when running on Ubuntu 

![Screenshot from 2021-09-09 09-39-47](https://user-images.githubusercontent.com/10088733/132608368-25d6b8e6-69e3-4695-bf8a-0e7177360d22.png)

I also tried [FDD](https://docs.microsoft.com/en-us/dotnet/core/deploying/deploy-with-cli#framework-dependent-deployment) deployment or [copyused](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming-options#trimming-granularity) trimmode,  got the same result.

would you like to give me some instructions?
thanks in advance

**Comment by wdcossey** [comment]
Hi @goodtogood,

I'll have a look at it this evening for you, I'll reply here with my findings.

**Comment by wdcossey** [comment]
@goodtogood 

I found the issue, was excluding `SciterCreateWindow` from Linux (and MacOS), it should be there for all operating systems.

You can grab the latest source and/or NuGet packages, this should resolve your issue.

**Comment by goodtogood** [comment]
Hi @wdcossey 
thank you so much, It works well on linux now.
another question, is there a way to disable the terminal window via code when running the app?

**Comment by wdcossey** [comment]
Hi @goodtogood 

Have a look at NSubsys on NuGet and see if this solves your issue?

https://www.nuget.org/packages/NSubsys

https://github.com/jmacato/NSubsys

From the repo:
'The patching process will only be done on Self-contained Publish. Running the project on Debug or Release mode wont trigger the package.'

Give this a whirl (I can't test it at the moment), if it works I'll update the readme to point other users in the right direction.

**Comment by goodtogood** [comment]
Hi @wdcossey 
I tried as you mentioned
It seems that it didn't work , no matter published via SCD with/without trimmed
thanks again .
