### ISSUE TITLE
Texts and Images Lose of quality/pixels at Runtime in SciterCore.JS.HelloSciter Sample Project

### ISSUE THREAD

**Issue by Elikar-KM** [wdcossey/SciterCore#52]
Hello Team, i tried all [samples](https://github.com/wdcossey/SciterCore/tree/master/Samples) and i say many thanks, all are good
However, when i compare [SciterCore.JS.HelloSciter](https://github.com/wdcossey/SciterCore/tree/master/Samples/SciterCore.JS/SciterCore.JS.HelloSciter) output user interface with other project, i see that text, images lose quality, please help for this.

I'm using VS2022 Version 17.1.0 Preview 1.1 in Microsoft Windows 11 Pro Version: 10.0.21996
Screen Resolution 2880 x 1620 
Scale : 200%
I have tested also in Windows 10 H2, same issue

See Example Image Output:
---------------------------------
[Js Core Sample Printed Picture Output](https://ibb.co/kmZwpcM)
[Winform Core Sample Printed Picture Output](https://ibb.co/Jm5b39b)

**Comment by wdcossey** [comment]
Hi @Elikar-KM 

I will have a look at this for you, that said they should all behave the same as the underlying code is the same.

1. What operating system are you using (Windows x ?)?
2. Are you using any scaling on your desktop (i.e. 125%)?

Any information would be helpful.

**Comment by wangkai2014** [comment]
Hi, I find this problem too

My Pc is windows 10 20H2 , my monitor is 4K27'' and desktop scale 225% , but scitercore.wpf have not this problem

**Comment by wdcossey** [comment]
I will have a look as soon as I'm on my Windows PC, might be a WinForms issue and not Sciter(JS).

**Comment by wangkai2014** [comment]
I solved it, it need to set this:

    <PropertyGroup>
        <ApplicationManifest>dpi-aware.manifest</ApplicationManifest>
    </PropertyGroup>



dpi-aware.manifest:

```
<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
    <asmv3:windowsSettings
         xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2, PerMonitor</dpiAwareness>
    </asmv3:windowsSettings>
  </asmv3:application>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
        <application> 
            <!-- Windows 10 --> 
            <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
            <!-- Windows 8.1 -->
            <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
            <!-- Windows Vista -->
            <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/> 
            <!-- Windows 7 -->
            <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
            <!-- Windows 8 -->
            <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
        </application> 
  </compatibility>
  <dependency>
      <dependentAssembly>
          <assemblyIdentity
              type="win32"
              name="Microsoft.Windows.Common-Controls"
              version="6.0.0.0"
              processorArchitecture="*"
              publicKeyToken="6595b64144ccf1df"
              language="*"
          />
      </dependentAssembly>
  </dependency>
</assembly>

```

**Comment by Elikar-KM** [comment]
> I solved it, it need to set this:
> 
> ```
> <PropertyGroup>
>     <ApplicationManifest>dpi-aware.manifest</ApplicationManifest>
> </PropertyGroup>
> ```
> 
> dpi-aware.manifest:
> 
> ```
> <?xml version='1.0' encoding='UTF-8' standalone='yes'?>
> <assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
>   <asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
>     <asmv3:windowsSettings
>          xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
>       <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/PM</dpiAware>
>       <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2, PerMonitor</dpiAwareness>
>     </asmv3:windowsSettings>
>   </asmv3:application>
>   <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1"> 
>         <application> 
>              
>             <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
>             
>             <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
>             
>             <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/> 
>             
>             <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
>             
>             <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
>         </application> 
>   </compatibility>
>   <dependency>
>       <dependentAssembly>
>           <assemblyIdentity
>               type="win32"
>               name="Microsoft.Windows.Common-Controls"
>               version="6.0.0.0"
>               processorArchitecture="*"
>               publicKeyToken="6595b64144ccf1df"
>               language="*"
>           />
>       </dependentAssembly>
>   </dependency>
> </assembly>
> ```

Yes yes, thanks... i added this to my project, its work good.

**Comment by Elikar-KM** [comment]
> Hi, I find this problem too
> 
> My Pc is windows 10 20H2 , my monitor is 4K27'' and desktop scale 225% , but scitercore.wpf have not this problem

I come to apply the wangkai2014

> Hi @Elikar-KM
> 
> I will have a look at this for you, that said they should all behave the same as the underlying code is the same.
> 
> 1. What operating system are you using (Windows x ?)?
> 2. Are you using any scaling on your desktop (i.e. 125%)?
> 
> Any information would be helpful.

I come to make changes made by [wangkai2014](https://github.com/wangkai2014), it working good.

**Comment by Elikar-KM** [comment]
Thanks for your help, you save me.
